### ISSUE TITLE
publish-draft fails when the Dashboard has an id

### ISSUE THREAD

**Issue by martinm-nm** [nearmap/libddog#35]
## Describe the bug

Passing a `Dashboard` with an `id` causes an exception:

```
    dashboard = Dashboard(
        title="libddog skel: AWS ELB dashboard",
        id="abc",
        desc="Sample dashboard showing metrics from ELB",
        widgets=[cpu_per_az],
        tmpl_var_presets=tmpl_presets_region,
    )
```

When running `publish-draft` we see:

```
$ ddog dash publish-draft -t '*skel*'
Creating dashboard entitled: '[draft] libddog skel: AWS ELB dashboard'... Traceback (most recent call last):
  File "/home/mmatusiak/envs/monitoring-project/lib/python3.8/site-packages/datadog/api/api_client.py", line 198, in submit
    response_obj = json.loads(content.decode("utf-8"))
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 4 column 1 (char 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mmatusiak/envs/monitoring-project/bin/ddog", line 169, in <module>
    cli()
  File "/home/mmatusiak/envs/monitoring-project/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/mmatusiak/envs/monitoring-project/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/mmatusiak/envs/monitoring-project/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mmatusiak/envs/monitoring-project/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mmatusiak/envs/monitoring-project/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mmatusiak/envs/monitoring-project/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/mmatusiak/envs/monitoring-project/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/mmatusiak/envs/monitoring-project/bin/ddog", line 110, in publish_draft
    exit_code = mgr.publish_draft(title_pat=title)
  File "/home/mmatusiak/envs/monitoring-project/lib/python3.8/site-packages/libddog/command_line/dashboards.py", line 195, in publish_draft
    id = self.manager.create_dashboard(dashboard=dash)
  File "/home/mmatusiak/envs/monitoring-project/lib/python3.8/site-packages/libddog/crud/dashboards.py", line 166, in create_dashboard
    return self.client.create_dashboard(dashboard=dashboard)
  File "/home/mmatusiak/envs/monitoring-project/lib/python3.8/site-packages/libddog/crud/client.py", line 54, in create_dashboard
    resp = datadog.api.Dashboard.create(**client_kwargs)  # type: ignore
  File "/home/mmatusiak/envs/monitoring-project/lib/python3.8/site-packages/datadog/api/resources.py", line 50, in create
    return APIClient.submit("POST", path, api_version, body, attach_host_name=attach_host_name, **params)
  File "/home/mmatusiak/envs/monitoring-project/lib/python3.8/site-packages/datadog/api/api_client.py", line 202, in submit
    raise ValueError("Invalid JSON response: {0}".format(content))
ValueError: Invalid JSON response: b'\n\n\n<!DOCTYPE html>
```

**Comment by martinm-nm** [comment]
In this scenario `publish-live` also fails with the same error:

```
$ ddog dash publish-live -t '*skel*'
Creating dashboard entitled: 'libddog skel: AWS ELB dashboard'... Traceback (most recent call last):
  File "/home/mmatusiak/envs/monitoring-project/lib/python3.8/site-packages/datadog/api/api_client.py", line 198, in submit
    response_obj = json.loads(content.decode("utf-8"))
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 4 column 1 (char 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mmatusiak/envs/monitoring-project/bin/ddog", line 169, in <module>
    cli()
  File "/home/mmatusiak/envs/monitoring-project/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/mmatusiak/envs/monitoring-project/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/mmatusiak/envs/monitoring-project/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mmatusiak/envs/monitoring-project/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mmatusiak/envs/monitoring-project/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mmatusiak/envs/monitoring-project/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/mmatusiak/envs/monitoring-project/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/mmatusiak/envs/monitoring-project/bin/ddog", line 133, in publish_live
    exit_code = mgr.publish_live(title_pat=title)
  File "/home/mmatusiak/envs/monitoring-project/lib/python3.8/site-packages/libddog/command_line/dashboards.py", line 235, in publish_live
    id = self.manager.create_dashboard(dashboard=dash)
  File "/home/mmatusiak/envs/monitoring-project/lib/python3.8/site-packages/libddog/crud/dashboards.py", line 166, in create_dashboard
    return self.client.create_dashboard(dashboard=dashboard)
  File "/home/mmatusiak/envs/monitoring-project/lib/python3.8/site-packages/libddog/crud/client.py", line 54, in create_dashboard
    resp = datadog.api.Dashboard.create(**client_kwargs)  # type: ignore
  File "/home/mmatusiak/envs/monitoring-project/lib/python3.8/site-packages/datadog/api/resources.py", line 50, in create
    return APIClient.submit("POST", path, api_version, body, attach_host_name=attach_host_name, **params)
  File "/home/mmatusiak/envs/monitoring-project/lib/python3.8/site-packages/datadog/api/api_client.py", line 202, in submit
    raise ValueError("Invalid JSON response: {0}".format(content))
ValueError: Invalid JSON response: b'\n\n\n<!DOCTYPE html>
```

**Comment by martinm-nm** [comment]
`publish-draft` first scans existing dashboards trying to detect if the dashboard we are publishing exists already. It does this matching by title. If it doesn't find a matching existing dashboard it takes the `create` code path:

```
Creating dashboard entitled: '[draft] libddog skel: AWS ELB dashboard'...
```

But since the Dashboard object does have an `id`, this `id` becomes part of the json document that is posted to the Datadog API and results in `POST https://api.datadoghq.com/api/v1/dashboard/abc` instead of `POST https://api.datadoghq.com/api/v1/dashboard/`. The Datadog API returns a 404 response, in HTML format, which can't even be interpreted as json and that's the exception we see.

`publish-live` fails in the same way.
